---

- name: Includeing OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- include: install.yml
  tags:
    - networking
    - vsftpd
    - install
    - vsftpd-install

- include: config.yml
  tags:
    - networking
    - vsftpd
    - config
    - vsftpd-config

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: service.yml
  tags:
    - networking
    - vsftpd
    - service
    - vsftpd-service

- include: manage.yml
  tags:
    - networking
    - vsftpd
    - manage
    - vsftpd-manage

- name: Ensure vsftpd is started and enabled to start at boot.
  service: name=vsftpd state=started enabled=yes
