---

- name: Includeing OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- include: install.yml
  tags:
    - networking
    - vsftpd
    - install
    - vsftpd-install

- include: config.yml
  tags:
    - networking
    - vsftpd
    - config
    - vsftpd-config

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: manage.yml
  tags:
    - networking
    - vsftpd
    - manage
    - vsftpd-manage

- include: service.yml
  tags:
    - networking
    - vsftpd
    - service
    - vsftpd-service
