---

- name: Managing users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.comment | default(item.username) }}"
    password: "{{ item.password }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    shell: /usr/sbin/nologin
  with_items: "{{ vsftpd_users }}"
